pipeline {
    agent any
    
    tools{
        maven 'maven 3.9.8' 
        }

    stages {
        stage("build"){
            when{
                changeset "**/worker/**"
            }
            steps{
                    echo "Compiling Worker App"
                    dir('worker'){
                        sh 'mvn compile'
                    }
                }
            }
            stage("test"){
                when{
                    changeset "**/worker/**"
                }
                steps{
                    echo 'Running Unit Test on Worker App'
                    dir('worker'){
                        sh 'mvn clean test'
                    }
                }
            }
            stage("package"){
                when{
                    branch 'master'
                    changeset "**/worker/**"
                }
                steps{
                    echo 'Packaging Worker App'
                    dir('worker'){
                        sh 'mvn package'
                        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    }
                }
            }
        }

        post{
            always{
                echo "Building MultiBranch Pipeline for Worker is Completed"
            }
        }
    }
